### ISSUE TITLE
Reformatting

### ISSUE THREAD

**Issue by novacourtois** [setholito/gulp-template#1]
You should just add all of the dependencies to your package.json file. 

Since you don't have one, just do

`npm install`

Follow the instructions, then run 

`npm install --save-dev gulp gulp-util gulp-sass gulp-clean-css gulp-jshint gulp-concat gulp-uglify gulp-livereload`

This will get them loaded into package.json
Then, whenever you clone it: all you have to do is:

`npm install`

and you'll be good to go.

**Comment by setholito** [comment]
Hey @novacourtois - That's a great thought! 
Thanks for looking this over, I'll make changes when I can.
